# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200122_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nssame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
            ],
        ),
    ]
