# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-22 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200122_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
